### ISSUE TITLE
Idea/rfe: use bz2 compression instead of gzip

### ISSUE THREAD

**Issue by isimluk** [openshift/scapresults#7]
Currently this container uses [gzip](https://github.com/openshift/scapresults/blob/cfe4fe018630d4aeefb32411510c97ea1bbefddc/cmd/scapresults/main.go#L139-L151). In the openscap ecosystem bz2 compression is used heavily and `oscap` command can process bz2 files natively.

For instance
 - openscap can tell details about bzip2ed arf: `oscap info /tmp/arf.xml.bz2`
 - openscap can generate HTML report out of bzip2ed arf: `oscap xccdf generate report --output /tmp/report.html /tmp/arf.xml.bz2`
 - openscap can generate remediation out of bzip2ed arf: `oscap xccdf generate fix --result-id '' /tmp/arf.xml.bz2`
 - you can validate bzip2ed arf: `oscap ds rds-validate /tmp/arf.xml.bz2` 
 - you can even decompose bzip2ed arf: `oscap ds rds-split /tmp/arf.xml.bz2 /tmp/out`

On top of that, some vendors already produce SCAP DataStreams and OVAL files bzip2ed. For instance see: https://www.redhat.com/security/data/oval/v2/RHEL7/ or https://www.redhat.com/security/data/metrics/ds/v2/RHEL8/

**Comment by jhrozek** [comment]
This was addressed by https://github.com/openshift/scapresults/pull/9
